// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/calendar/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all calendars from the user's connected Google account.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Calendar"
                ],
                "summary": "List Google Calendars",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_application_query_calendar.CalendarInfo"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/calendar/me/events": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new event in the user's connected Google Calendar.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Calendar"
                ],
                "summary": "Create calendar event",
                "parameters": [
                    {
                        "description": "Event data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_controller_calendar.CreateEventRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_controller_calendar.CreateEventResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/integrations/google/callback": {
            "get": {
                "description": "Receives the OAuth authorization code from Google and stores the access token.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Integrations"
                ],
                "summary": "Google OAuth callback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "OAuth state parameter",
                        "name": "state",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "OAuth authorization code",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Google connected ✓",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/integrations/google/connect": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Redirects the authenticated user to Google OAuth consent screen.",
                "tags": [
                    "Integrations"
                ],
                "summary": "Connect Google Calendar",
                "responses": {
                    "302": {
                        "description": "Redirect to Google OAuth"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/nutrition/entries": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all diary entries for the authenticated user on a given date (default: today).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Nutrition"
                ],
                "summary": "List nutrition diary entries",
                "parameters": [
                    {
                        "type": "string",
                        "example": "2024-03-15",
                        "description": "Date in YYYY-MM-DD format",
                        "name": "date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_domain_model.DiaryEntry"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Records a meal with food items for the authenticated user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Nutrition"
                ],
                "summary": "Create nutrition diary entry",
                "parameters": [
                    {
                        "description": "Diary entry",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_controller_nutrition.CreateEntryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_domain_model.DiaryEntry"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/nutrition/entries/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a single diary entry by ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Nutrition"
                ],
                "summary": "Get nutrition diary entry",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Entry ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_domain_model.DiaryEntry"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Replaces the meal type and food items of an existing diary entry.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Nutrition"
                ],
                "summary": "Update nutrition diary entry",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Entry ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated entry data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_controller_nutrition.UpdateEntryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_domain_model.DiaryEntry"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a diary entry belonging to the authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Nutrition"
                ],
                "summary": "Delete nutrition diary entry",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Entry ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/profiles/coach": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the coach profile of the authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profiles"
                ],
                "summary": "Get coach profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_domain_model.CoachProfile"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Replaces the coach profile for the authenticated user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profiles"
                ],
                "summary": "Update coach profile",
                "parameters": [
                    {
                        "description": "Updated coach profile data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_controller_profiles.UpdateCoachProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_domain_model.CoachProfile"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a coach profile for the authenticated user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profiles"
                ],
                "summary": "Create coach profile",
                "parameters": [
                    {
                        "description": "Coach profile data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_controller_profiles.CreateCoachProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_domain_model.CoachProfile"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/profiles/user": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the fitness profile of the authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profiles"
                ],
                "summary": "Get user profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_domain_model.UserProfile"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Replaces the fitness profile for the authenticated user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profiles"
                ],
                "summary": "Update user profile",
                "parameters": [
                    {
                        "description": "Updated profile data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_controller_profiles.UpdateUserProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_domain_model.UserProfile"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a fitness profile for the authenticated user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profiles"
                ],
                "summary": "Create user profile",
                "parameters": [
                    {
                        "description": "User profile data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_controller_profiles.CreateUserProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_domain_model.UserProfile"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/programs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all training programs belonging to the authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Programs"
                ],
                "summary": "List training programs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_domain_model.TrainingProgram"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new training program with optional days and exercises.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Programs"
                ],
                "summary": "Create training program",
                "parameters": [
                    {
                        "description": "Program data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_controller_programs.CreateProgramRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_domain_model.TrainingProgram"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/programs/progress": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Records a completed set of an exercise for the authenticated user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Programs"
                ],
                "summary": "Track exercise progress",
                "parameters": [
                    {
                        "description": "Progress data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_controller_programs.TrackProgressRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_domain_model.ExerciseProgress"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/programs/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a training program by ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Programs"
                ],
                "summary": "Get training program",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Program ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_domain_model.TrainingProgram"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a training program owned by the authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Programs"
                ],
                "summary": "Delete training program",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Program ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/check": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the user ID and role extracted from the JWT token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Check auth token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_controller_authorize.CheckResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "description": "Authenticates the user and returns a JWT token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_controller_authorize.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_application_command_authorize.LoginUserResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Revokes the current JWT token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/register": {
            "post": {
                "description": "Creates a new account and returns a JWT token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Registration payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_controller_authorize.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_application_command_authorize.RegisterUserResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/reset-password": {
            "patch": {
                "description": "Resets the user password using a one-time reset token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Reset password",
                "parameters": [
                    {
                        "description": "Reset token and new password",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_controller_authorize.ResetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/send-email": {
            "post": {
                "description": "Sends a one-time password-reset link to the given email address.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Send password-reset email",
                "parameters": [
                    {
                        "description": "Email address",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_controller_authorize.SendEmailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_msskobelina_fit-profi_internal_application_command_authorize.LoginUserResult": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "userID": {
                    "type": "integer"
                }
            }
        },
        "github_com_msskobelina_fit-profi_internal_application_command_authorize.RegisterUserResult": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "userID": {
                    "type": "integer"
                }
            }
        },
        "github_com_msskobelina_fit-profi_internal_application_query_calendar.CalendarInfo": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                }
            }
        },
        "github_com_msskobelina_fit-profi_internal_delivery_controller.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "validation error message"
                }
            }
        },
        "github_com_msskobelina_fit-profi_internal_domain_model.CoachAchievement": {
            "type": "object",
            "properties": {
                "certificateUrl": {
                    "type": "string"
                },
                "coachProfileId": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "endPeriod": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "startPeriod": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_msskobelina_fit-profi_internal_domain_model.CoachCategory": {
            "type": "string",
            "enum": [
                "standard",
                "master",
                "professional"
            ],
            "x-enum-varnames": [
                "CoachStandard",
                "CoachMaster",
                "CoachPro"
            ]
        },
        "github_com_msskobelina_fit-profi_internal_domain_model.CoachEducation": {
            "type": "object",
            "properties": {
                "coachProfileId": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "endPeriod": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "place": {
                    "type": "string"
                },
                "startPeriod": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_msskobelina_fit-profi_internal_domain_model.CoachProfile": {
            "type": "object",
            "properties": {
                "achievements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_domain_model.CoachAchievement"
                    }
                },
                "category": {
                    "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_domain_model.CoachCategory"
                },
                "createdAt": {
                    "type": "string"
                },
                "education": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_domain_model.CoachEducation"
                    }
                },
                "fullName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "info": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "github_com_msskobelina_fit-profi_internal_domain_model.DiaryEntry": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_domain_model.DiaryItem"
                    }
                },
                "mealType": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "github_com_msskobelina_fit-profi_internal_domain_model.DiaryItem": {
            "type": "object",
            "properties": {
                "calories": {
                    "type": "number"
                },
                "carbsG": {
                    "type": "number"
                },
                "createdAt": {
                    "type": "string"
                },
                "entryId": {
                    "type": "integer"
                },
                "fatG": {
                    "type": "number"
                },
                "grams": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "proteinG": {
                    "type": "number"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_msskobelina_fit-profi_internal_domain_model.ExerciseProgress": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "exerciseId": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "notes": {
                    "type": "string"
                },
                "reps": {
                    "type": "integer"
                },
                "sets": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                },
                "weightKg": {
                    "type": "integer"
                }
            }
        },
        "github_com_msskobelina_fit-profi_internal_domain_model.Goal": {
            "type": "string",
            "enum": [
                "lose_weight",
                "gain_weight",
                "rehab",
                "keep_fit",
                "competition"
            ],
            "x-enum-varnames": [
                "GoalLoseWeight",
                "GoalGainWeight",
                "GoalRehab",
                "GoalKeepFit",
                "GoalCompetition"
            ]
        },
        "github_com_msskobelina_fit-profi_internal_domain_model.ProgramDay": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "dayNumber": {
                    "type": "integer"
                },
                "exercises": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_domain_model.ProgramExercise"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "programId": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_msskobelina_fit-profi_internal_domain_model.ProgramExercise": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "dayId": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "reps": {
                    "type": "integer"
                },
                "sets": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "weightKg": {
                    "type": "integer"
                }
            }
        },
        "github_com_msskobelina_fit-profi_internal_domain_model.TrainingProgram": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "days": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_domain_model.ProgramDay"
                    }
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "github_com_msskobelina_fit-profi_internal_domain_model.UserProfile": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "goal": {
                    "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_domain_model.Goal"
                },
                "id": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                },
                "weightKg": {
                    "type": "number"
                }
            }
        },
        "internal_delivery_controller_authorize.CheckResponse": {
            "type": "object",
            "properties": {
                "role": {
                    "type": "string",
                    "example": "user"
                },
                "userId": {
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "internal_delivery_controller_authorize.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "secret123"
                }
            }
        },
        "internal_delivery_controller_authorize.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "fullName",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "fullName": {
                    "type": "string",
                    "example": "John Doe"
                },
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "secret123"
                }
            }
        },
        "internal_delivery_controller_authorize.ResetPasswordRequest": {
            "type": "object",
            "required": [
                "password",
                "token"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "newSecret123"
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiJ9..."
                }
            }
        },
        "internal_delivery_controller_authorize.SendEmailRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                }
            }
        },
        "internal_delivery_controller_calendar.CreateEventRequest": {
            "type": "object",
            "required": [
                "end",
                "start",
                "title"
            ],
            "properties": {
                "attendees": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "coach@example.com"
                    ]
                },
                "calendarId": {
                    "type": "string",
                    "example": "primary"
                },
                "end": {
                    "type": "string",
                    "example": "2024-03-15T11:00:00Z"
                },
                "notes": {
                    "type": "string",
                    "example": "Leg day"
                },
                "reminders": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        10,
                        30
                    ]
                },
                "start": {
                    "type": "string",
                    "example": "2024-03-15T10:00:00Z"
                },
                "title": {
                    "type": "string",
                    "example": "Training session"
                }
            }
        },
        "internal_delivery_controller_calendar.CreateEventResult": {
            "type": "object",
            "properties": {
                "eventId": {
                    "type": "string",
                    "example": "abc123xyz"
                }
            }
        },
        "internal_delivery_controller_nutrition.CreateEntryRequest": {
            "type": "object",
            "required": [
                "date",
                "items",
                "mealType"
            ],
            "properties": {
                "date": {
                    "type": "string",
                    "example": "2024-03-15"
                },
                "items": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_domain_model.DiaryItem"
                    }
                },
                "mealType": {
                    "type": "string",
                    "enum": [
                        "breakfast",
                        "lunch",
                        "dinner",
                        "snack"
                    ],
                    "example": "lunch"
                }
            }
        },
        "internal_delivery_controller_nutrition.UpdateEntryRequest": {
            "type": "object",
            "required": [
                "items",
                "mealType"
            ],
            "properties": {
                "items": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_domain_model.DiaryItem"
                    }
                },
                "mealType": {
                    "type": "string",
                    "enum": [
                        "breakfast",
                        "lunch",
                        "dinner",
                        "snack"
                    ],
                    "example": "dinner"
                }
            }
        },
        "internal_delivery_controller_profiles.CreateCoachProfileRequest": {
            "type": "object",
            "required": [
                "category",
                "fullName",
                "info"
            ],
            "properties": {
                "achievements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_domain_model.CoachAchievement"
                    }
                },
                "category": {
                    "type": "string",
                    "enum": [
                        "standard",
                        "master",
                        "professional"
                    ],
                    "example": "master"
                },
                "education": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_domain_model.CoachEducation"
                    }
                },
                "fullName": {
                    "type": "string",
                    "example": "Jane Smith"
                },
                "info": {
                    "type": "string",
                    "example": "10 years of coaching experience"
                }
            }
        },
        "internal_delivery_controller_profiles.CreateUserProfileRequest": {
            "type": "object",
            "required": [
                "age",
                "fullName",
                "goal",
                "weightKg"
            ],
            "properties": {
                "age": {
                    "type": "integer",
                    "example": 25
                },
                "description": {
                    "type": "string",
                    "example": "I want to stay healthy"
                },
                "fullName": {
                    "type": "string",
                    "example": "John Doe"
                },
                "goal": {
                    "type": "string",
                    "enum": [
                        "lose_weight",
                        "gain_weight",
                        "rehab",
                        "keep_fit",
                        "competition"
                    ],
                    "example": "keep_fit"
                },
                "weightKg": {
                    "type": "number",
                    "example": 75.5
                }
            }
        },
        "internal_delivery_controller_profiles.UpdateCoachProfileRequest": {
            "type": "object",
            "required": [
                "category",
                "fullName",
                "info"
            ],
            "properties": {
                "achievements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_domain_model.CoachAchievement"
                    }
                },
                "category": {
                    "type": "string",
                    "enum": [
                        "standard",
                        "master",
                        "professional"
                    ],
                    "example": "professional"
                },
                "education": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_domain_model.CoachEducation"
                    }
                },
                "fullName": {
                    "type": "string",
                    "example": "Jane Smith"
                },
                "info": {
                    "type": "string",
                    "example": "Updated bio"
                }
            }
        },
        "internal_delivery_controller_profiles.UpdateUserProfileRequest": {
            "type": "object",
            "required": [
                "age",
                "fullName",
                "goal",
                "weightKg"
            ],
            "properties": {
                "age": {
                    "type": "integer",
                    "example": 26
                },
                "description": {
                    "type": "string",
                    "example": "Updated description"
                },
                "fullName": {
                    "type": "string",
                    "example": "John Doe"
                },
                "goal": {
                    "type": "string",
                    "enum": [
                        "lose_weight",
                        "gain_weight",
                        "rehab",
                        "keep_fit",
                        "competition"
                    ],
                    "example": "lose_weight"
                },
                "weightKg": {
                    "type": "number",
                    "example": 74
                }
            }
        },
        "internal_delivery_controller_programs.CreateProgramRequest": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "days": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_msskobelina_fit-profi_internal_domain_model.ProgramDay"
                    }
                },
                "description": {
                    "type": "string",
                    "example": "3-day full-body routine"
                },
                "title": {
                    "type": "string",
                    "example": "Beginner Full Body"
                }
            }
        },
        "internal_delivery_controller_programs.TrackProgressRequest": {
            "type": "object",
            "required": [
                "exerciseId",
                "reps",
                "sets"
            ],
            "properties": {
                "exerciseId": {
                    "type": "integer",
                    "example": 5
                },
                "notes": {
                    "type": "string",
                    "example": "Felt strong today"
                },
                "reps": {
                    "type": "integer",
                    "example": 12
                },
                "sets": {
                    "type": "integer",
                    "example": 3
                },
                "weightKg": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 60
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter: Bearer \u003ctoken\u003e",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "localhost:8086",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "FitProfi API",
	Description:      "Fitness platform REST API — training programs, nutrition diary, Google Calendar integration.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
